---

- name: Start tableau
  command: "{{ TSM_EXECUTABLE }}/tsm start"

- name: Stop tableau
  command: "{{ TSM_EXECUTABLE }}/tsm stop"

- name: Apply pending changes
  command: "{{ TSM_EXECUTABLE }}/tsm pending-changes apply -r --username {{ tableau_user }} --password {{ tableau_password }}"
