---

- name: TABLEAU INSTALL | Install on Debian environment (This may take some time)
  apt:
    deb: "{{ tableau_url_deb }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: TABLEAU INSTALL | Install on RedHat environment (This may take some time)
  yum:
    name: "{{ tableau_url_rpm }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: TABLEAU INSTALL | Get Tableau TSM version
  shell: "ls {{ tsm_packages }} | grep scripts"
  register: tsm
  changed_when: false

- name: TABLEAU INSTALL | Fix systemd unit
  lineinfile:
    path: "{{ tsm_packages }}/{{ tsm.stdout }}/user-at.service"
    line: Environment=XDG_RUNTIME_DIR=/run/user/%i
    insertbefore: "^ExecStart="
    state: present
  when: tableau_fix_systemd_unit

- name: TABLEAU INSTALL | Initialize Tableau TSM
  command: ./initialize-tsm {{ tsm_execute_args }} -f
  args:
    chdir: "{{ tsm_packages }}/{{ tsm.stdout }}"
    creates: "{{ tableau_data_dir }}"
